export const COUNTRIES = [
    "Argentina",
    "Aruba",
    "Bolivia",
    "Brasil",
    "Canadá",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Curazao",
    "Ecuador",
    "El Salvador",
    "España",
    "Estados Unidos (USA)",
    "Guatemala",
    "Honduras",
    "México",
    "Nicaragua",
    "Panamá",
    "Paraguay",
    "Perú",
    "Puerto Rico",
    "República Dominicana",
    "Trinidad y Tobago",
    "Uruguay",
    "Venezuela",
] as const;

export const COLOMBIAN_CHAPTERS = [
    "Armenia",
    "Barranquilla",
    "Bogotá",
    "Bucaramanga",
    "Cali",
    "Cartagena",
    "Cúcuta",
    "Duitama",
    "Floridablanca",
    "Ibagué",
    "Manizales",
    "Medellín",
    "Mocoa",
    "Neiva",
    "Pasto",
    "Pereira",
    "Popayán",
    "Puerto Colombia",
    "Sabana",
    "Valle de Aburrá",
    "Zenu",
] as const;
