export const COUNTRIES = [
    "Argentina",
    "Aruba",
    "Bolivia",
    "Brasil",
    "Canadá",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Curazao",
    "Ecuador",
    "El Salvador",
    "España",
    "Estados Unidos (USA)",
    "Guatemala",
    "Honduras",
    "México",
    "Nicaragua",
    "Panamá",
    "Paraguay",
    "Perú",
    "Puerto Rico",
    "República Dominicana",
    "Trinidad y Tobago",
    "Uruguay",
    "Venezuela",
] as const;

export const CHAPTERS_BY_COUNTRY: Record<string, string[]> = {
    "Argentina": ["Aconcagua", "Buenos Aires", "Mar del Plata", "Mendoza", "Rio Gallegos"],
    "Bolivia": ["Cochabamba", "Santa Cruz de la Sierra", "Urubo"],
    "Brasil": ["Anapolis", "Aparecida", "Goiania", "Rio de Janeiro"],
    "Chile": ["Antofagasta", "Rancagua", "Valparaiso", "Viña del Mar"],
    "Colombia": ["Armenia", "Barranquilla", "Bogotá", "Bucaramanga", "Cali", "Cartagena", "Cúcuta", "Duitama", "Floridablanca", "Ibagué", "Manizales", "Medellín", "Mocoa", "Neiva", "Pasto", "Pereira", "Popayán", "Puerto Colombia", "Sabana", "Valle de Aburrá", "Zenú"],
    "Ecuador": ["Babahoyo", "Cuenca", "Guayaquil", "Lagoagrio", "Manta", "Otavalo", "Portoviejo", "Quito", "Riobamba", "Valles"],
    "Peru": ["Arequipa", "Lima"],
    "Uruguay": ["Cupe", "Las Piedras", "Montevideo", "Rivera"],
    "Venezuela": ["Barquisimeto", "Caracas", "Maturin", "Merida", "San Cristobal", "Tucupita", "Valencia"],
};
